# Generated by Django 6.0.6 on 2026-06-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_routes_route'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='route',
            table='routes',
        ),
    ]
